# head
menu:
  目录: /archives
  # sitemap: /sitemap.xml
  # other menus

rss: /atom.xml
favicon: /favicon.ico

date_format: 'MMMM D, YYYY'

google_verification: false  # your token
google_analytics: UA-56273324-3     # your id

disqus_shortname: zhu-fan-er-ji-zhu-tuan-dui     # your disqus name

live2d: false    # true
hjid: false      # your hjid (hotjar)

start_year: 2017